### ISSUE TITLE
save.image after grayscale results in black images

### ISSUE THREAD

**Issue by wittmaan** [dahtah/imager#30]
Hello everybody, 
when i try to save an image

``` R
library(imager) 
fpath <- system.file('extdata/Leonardo_Birds.jpg',package='imager') 
im <- load.image(fpath)
save.image(im, "test.jpg")
```

everything, went's fine, but if i change the last row with 

``` R
save.image(grayscale(im), "test.jpg")
```

i get an black image. Missed i something or is it a bug?

best regards
Andreas

**Comment by dahtah** [comment]
Hi Andreas,

Not really a bug, just an annoyance due to R using the 0-1 range for 
RGB, and other software using 0-255. If you try range(im) you'll see 
it's in 0-1.
save.image expects RGB values to be in 0-255.
It's a source of confusion, though, I'll try to enforce better default 
behaviour and issue some warnings.

Best

Simon

**Comment by akb13** [comment]
Hello, 

I am having the same issue and I'm not sure how to get around it. Is there something that can be changed in order to save a grayscale image that is not black?

**Comment by dahtah** [comment]
@akb13 : yes. Assuming the image values were initially encoded in the 0-1 range, just multiply the image by 255. 
``` save.image(im*255) ```
should do the trick. 

In the next version of imager everything will be standardised to a 0-1 range for RGB.
