### ISSUE TITLE
fsize in draw_text

### ISSUE THREAD

**Issue by sorrynoclue42** [dahtah/imager#94]
Hi, I'm having trouble with the font size in draw_text: no matter what value I put enter for fsize = , there is no change in the size of the font on the image. I'm running R version 3.5.3 and imager version 0.41.2 on Windows (64 bit). Any comments?

**Comment by ShotaOchi** [comment]
I confirmed that fsize didn't work.
The reason is obvious.
fsize is not passed to draw_text_ function in draw_text function.
We should eliminate the "=1" and "=20" in Line 136.
See the code shown below.
https://github.com/dahtah/imager/blob/7a71590cf88d34a3f5b2df22165a3a83e8b4a84b/R/drawing.R#L129-L137
